# Generated by Django 5.0 on 2023-12-15 14:30

import localflavor.gh.models
import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='region',
            field=localflavor.gh.models.GHRegionField(default='GR', max_length=13),
        ),
        migrations.AddField(
            model_name='locations',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='locations',
            name='address_1',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
