# Generated by Django 5.0 on 2023-12-16 23:19

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address_1_alter_user_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.user_photo_directory_path),
        ),
    ]
